quickSort: quicksort.cpp
	g++ -o QuickSort quicksort.cpp -lpthread

bubbleSort: bubblesort.c
	gcc -g -Wall -fopenmp -o BubbleSort bubblesort.c

mergeSort: merge-sort.cpp
	g++ -o MergeSort -lpthread merge-sort.cpp
